### ISSUE TITLE
Add an option to limit the rate of logged messages

### ISSUE THREAD

**Issue by LionelCons** [duritong/puppet-nftables#19]
The default logging of incoming packets comes from:
```
    'INPUT-log_discarded':
      order   => '97',
      content => "log prefix \"${sprintf($_log_prefix_discard, { 'chain' => 'INPUT' })}\" flags all counter";
```

This contains no rate limiting so this opens the door to DoS attacks.

All the rules that log something should use rate limiting, at least via an option.

**Comment by keachi** [comment]
That's a good point. Rate limit the logging via an option would be my preferred way. The default could then be enabled, but it should be possible to disable it.

**Comment by nbarrientos** [comment]
Yeah, it makes sense. What about this as default?

```
limit rate 3/minute burst 5 
```

of a parameter in `nftables`, say `nftables::log_rate`?

Happy to provide a patch once the pending merge requests have been cleared out.

**Comment by LionelCons** [comment]
LGTM
