### ISSUE TITLE
The fate of forbidden packets should be configurable

### ISSUE THREAD

**Issue by LionelCons** [duritong/puppet-nftables#2]
A forbidden packet is currently logged and denied. This is hard-coded in the 'INPUT-log_rejected' fragment and it is not configurable.

The fate of forbidden packets should be configurable.

This is especially important for the log prefix and the associated action (some may want to drop rather than reject).

**Comment by duritong** [comment]
Sounds reasonable, happy to merge a MR

**Comment by LionelCons** [comment]
FWIW, I have tested Nacho's `log_prefix` and `reject_with` and they work fine in my environment. So these 2 MRs do fix this issue.
