### ISSUE TITLE
Add an option to disable NAT

### ISSUE THREAD

**Issue by LionelCons** [duritong/puppet-nftables#23]
Most of what is instantiated by default can be disabled with the `$in_*` and `$out_*` variables. This is good and allows for a clean and minimal `nftables` configuration.

Unfortunately, the NAT related bits cannot be disabled. This creates two tables and four chains which are not used (by default).

It would be cleaner to have an option to remove all the NAT related code. `init.pp` could simply have something like:
```
if ($nat) {
    include nftables::ip_nat
}
```

**Comment by nbarrientos** [comment]
I'll send a patch.
